FROM nginx:alpine
COPY public/index.html    /usr/share/nginx/html/index.html
COPY public/login.html    /usr/share/nginx/html/login.html
COPY public/paquete.html  /usr/share/nginx/html/paquete.html
COPY assets/styles.css    /usr/share/nginx/html/styles.css
COPY assets/app.js        /usr/share/nginx/html/app.js
EXPOSE 80
